### ISSUE TITLE
can't install with python 3.11

### ISSUE THREAD

**Issue by benjschiller** [pysam-developers/pysam#1174] opened 2023-03-20 18:24 UTC
I haven't been able to install v0.20.0 with pip and python 3.11.2 (mac or ubuntu/Docker). I get these errors during build complaining of a deprecated distutils interface:

```
        File "/private/var/folders/kp/jkzzt1v9631db4lwg64kwszh0000gn/T/pip-install-hoeyu_k8/pysam_c7ba44538f624460bf9598df6b25fc84/cy_build.py", line 69, in build_extension
          relative_module_path = ext.name.replace(".", os.sep) + get_config_vars()["SO"]
                                                                 ~~~~~~~~~~~~~~~~~^^^^^^
      KeyError: 'SO'

```

I was able to install directly from the github repo tho, so I was wondering if you could cut a new v0.20.1 release from the main branch. If not, i'll put up a local pypi repo, but having an official release is easier for deployment. Thanks!

**Comment by jmarshall** [comment] 2023-03-20 20:07
Duplicate of #1154. If you read that issue and other recent activity, you'll see that a new release is imminent.

**Closed** 2023-03-20 20:08 UTC

**Comment by benjschiller** [comment] 2023-03-20 22:41
Thanks!
