### ISSUE TITLE
Bug: get_reference_sequence returns the wrong value

### ISSUE THREAD

**Issue by nh13** [pysam-developers/pysam#895] opened 2020-02-26 01:52 UTC
Below is an alignment I made up (query on top, target on the bottom):

```
AAAAAAAAAAACCC---AAAAAA--AAAAAAA-GGGTAAAAAACCCC---TTTTAAAAAA-AA
===X===X===IIIDDD===II=DD=XII===DXXXI======XIIIDDDXXXX===I==D==
AAACAAATAAA---GGGAAA--ATTAT--AAAAAAA-AAAAAAA---AAAAAAAAAA-AAAAA
```

Converting this to an AlignedSegment I get:

```
query_sequence = AAAAAAAAAAACCCAAAAAAAAAAAAAGGGTAAAAAACCCCTTTTAAAAAAAA
cigar = 11M3I3D3M2I1M2D2M2I3M1D3M1I7M3I3D7M1I2M1D2M
md = 3C3T3^GGG4^TT1T3^AAAA6A^AAAAAA6^A2
```

Value returned by get_reference_sequence() is:

```
AAAcAAAtAAAGGGAAAATTAtAAAAAAAAAAAAAaAAAAAAAAAAAAAAA
```

The expected value is:

```
AAAcAAAtAAAGGGAAAATTAtAAAAaaaAAAAAAaAAAaaaaAAAAAAAA
```

I think it is having trouble making mismatches after a deletion to be lowercase. I'd be happy to debug further if someone could write a pysam unit test that fails.

**Comment by nh13** [comment] 2020-02-26 03:55
Here's a `test.sam` file:

<details>

<summary>test.sam</summary>

```
@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:249250621
@RG	ID:1	SM:1_AAAAAA	LB:default	PU:xxx.1	PL:ILLUMINA
q0000	99	chr1	2	60	11M3I3D3M2I1M2D2M2I3M1D3M1I7M3I3D7M1I2M1D2M	=	2	51	AAAAAAAAAAACCCAAAAAAAAAAAAAGGGTAAAAAACCCCTTTTAAAAAAAA	?????????????????????????????????????????????????????	MD:Z:3C3T3^GGG4^TT1T3^AAAA6A^AAAAAAA5^A2	RG:Z:1	MC:Z:11M3I3D3M2I1M2D2M2I3M1D3M1I7M3I3D7M1I2M1D2M
q0000	147	chr1	2	60	11M3I3D3M2I1M2D2M2I3M1D3M1I7M3I3D7M1I2M1D2M	=	2	-51	AAAAAAAAAAACCCAAAAAAAAAAAAAGGGTAAAAAACCCCTTTTAAAAAAAA	?????????????????????????????????????????????????????	MD:Z:3C3T3^GGG4^TT1T3^AAAA6A^AAAAAAA5^A2	RG:Z:1	MC:Z:11M3I3D3M2I1M2D2M2I3M1D3M1I7M3I3D7M1I2M1D2M
```
</details>

**Comment by jmarshall** [comment] 2020-03-24 15:59
I think the problem here is the calculation of the MD value. Recall that in MD the single
bases (`[A-Z]`) / deletions (`\^[A-Z]+`) must **alternate** with the digits. So your MD value:

    md = 3C3T3^GGG4^TT1T3^AAAA6A^AAAAAA6^A2

indicates the following deletions: `GGG`, `TT`, `AAAA`, `AAAAAA`; the latter two are different from what you intended to represent. In particular you need a `0` setting off the deleted bases from an immediately following mismatch base; you also need a `0` between adjacent mismatches (it's harder to see why the spec — such as it is — requires this!). So the correct MD value here would be (as confirmed via `samtools calmd`, and with the too-short MD value alongside for comparison):

    bad md =  3C3T3^GGG4^TT1T3^AAAA6A^AAAAAA6^A2
    good md = 3C3T3^GGG4^TT1T3^A0A0A0A6A0^AAA0A0A0A0A5^A2

With this good MD value, the existing `get_reference_sequence()` code produces your expected value.

**Comment by nh13** [comment] 2020-03-30 18:12
@jmarshall From the [sam-tags](https://github.com/samtools/hts-specs/blob/master/SAMtags.tex#L184-L193) MD section, it is not clear that things need to be zero-padded.  For example, `10A5^AC6` is underspecified if a CIGAR is not given, since a cigar `10=1X5=1D1X6=` or `10=1X5=2D6=` could both "work" with the MD tag.  I think what you're saying is to disambiguate so you do not need a cigar, the former should be `10A5^A0C6` (with the `0` between the deletion and next mismatch), and the latter should be `10A5^AC6`.  I don't see this described in the spec.  I'm happy to add it to the spec, or move the discussion there.  Most likely I'm wrong somehow.

**Comment by jmarshall** [comment] 2020-04-01 23:07
Agreed that MD is woefully underspecified. Please do raise this as an hts-specs issue — but probably not a PR yet as we'll need to workshop the desired behaviour.

You are right that the CIGAR string can be used to pick the desired parsing of an otherwise ambiguous non-0-padded MD string. It is also the case that SEQ and MD cannot be used alone to reconstruct the reference sequence, as if nothing else you do need to parse CIGAR to use the `I` operators to omit any inserted bases present only in SEQ.

OTOH the spec regular expression for MD does clearly describe the strings of letters as **alternating** with the strings of digits. Based on what we know of the original spec author's penchant for conveying meaning via REs, and on what the contemporaneous implementation by the same author does (i.e., `samtools fillmd`, which 0-pads), I think it's fair to say that 0-padding is the spec's intention.

Was this MD string generated by a program, and if so, what program?

**Comment by nh13** [comment] 2020-04-02 00:17
@jmarshall these were added by hand, and a few tools that are now fixed.  Sometimes I need to write MD tags as part of a test case, and I find adding zero-padding less intuitive.  It's a minor gripe, very minor, so I think this can be closed for now.

**Comment by AndreasHeger** [comment] 2020-05-23 20:34
Thanks both, I will close the issue.

**Closed by AndreasHeger** 2020-05-23 20:34 UTC
