### ISSUE TITLE
Documentation on Read the Docs is outdated

### ISSUE THREAD

**Issue by marcelm** [pysam-developers/pysam#1043] opened 2021-09-14 15:40 UTC
It appears that the docs on RTD haven’t been updated in three years: https://readthedocs.org/projects/pysam/

There were some mails from RTD about a change in the API, perhaps that is the problem. I assume that the GitHub/RTD integration needs to be re-done.

**Comment by jmarshall** [comment] 2021-09-14 15:49
Duplicate of #1026

**Closed by jmarshall** 2021-09-14 15:49 UTC
