### ISSUE TITLE
0.13 release - CRAM iteration throws OSError: truncated file

### ISSUE THREAD

**Issue by egafni** [pysam-developers/pysam#567] opened 2017-11-09 00:32 UTC
Bam works fine using python 0.12.1 but the following fetch generates an error:

bam = pysam.AlignmentFile ('align.cram')
len(list(bam.fetch('chr8', 145100000, 145138636)))
  File "pysam/libcalignmentfile.pyx", line 1752, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file

iterating over the file is fine, and most regions are fine, but this one is broken

**Comment by AndreasHeger** [comment] 2017-11-10 09:58
Thanks. Not sure what could be the issue here, could you share the example data?

**Comment by egafni** [comment] 2017-11-12 06:41
I'm unable to share the data unfortunately.  Sorry I can't be more useful..

**Comment by AndreasHeger** [comment] 2017-11-17 11:08
Thanks, no worries. I will keep the ticket open, hopefully somebody else can reproduce the issue.
I will also rename it.

**Comment by ihaque-freenome** [comment] 2018-01-22 23:12
@AndreasHeger here's a small example data set that reproduces the issue on my end. It's subsampled data (~240k reads) from 1kG sample HG00114, realigned using bwa mem against reference [hs38DH](https://github.com/lh3/bwa/blob/master/bwakit/run-gen-ref).

[HG00114.0025.cram](https://drive.google.com/open?id=1NsCCl3xDaNCWObiS3rosPfxS7WEcCK6b)
[HG00114.0025.cram.crai](https://drive.google.com/open?id=1Il9vPw_EWc6V64e-niol1H8UsAILiyXI)

CRAM put together using samtools 1.5

test program (Python 3.5, pysam 0.13.0)
```python
import sys
import pysam
x = pysam.AlignmentFile(sys.argv[1], 'rc')
print(list(x.fetch('chr8', 145100000, 145138636)))
```

output: broken on CRAM, works on BAM
```
(test-pysam0.13) ihaque@frontend001:/tmp/ihaque/1kg$ python test.py HG00114.0025.cram
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(list(x.fetch('chr8', 145100000, 145138636)))
  File "pysam/libcalignmentfile.pyx", line 1752, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file

(test-pysam0.13) ihaque@frontend001:/tmp/ihaque/1kg$ samtools view -b -o HG00114.0025.bam HG00114.0025.cram

(test-pysam0.13) ihaque@frontend001:/tmp/ihaque/1kg$ samtools index HG00114.0025.bam

(test-pysam0.13) ihaque@frontend001:/tmp/ihaque/1kg$ python test.py HG00114.0025.bam
[]
```

**Comment by ihaque-freenome** [comment] 2018-01-22 23:17
And here's a pair of files that don't have the problem - generated by taking the above file and subsampling another 5x (~48k reads):

[HG00114.0005.cram](https://drive.google.com/open?id=146JapIgBr-_VHjTcrbRCmjCXX5jTvA_a)
[HG00114.0005.cram.crai](https://drive.google.com/open?id=1CRyTm3SSC6UwhZ5Ces9CZSNmvrTOf184)

**Comment by kyleabeauchamp** [comment] 2018-01-24 18:15
1.  I can reproduce the issue you described
2.  I can see possible issues when accessing that region of the CRAM using samtools (see below log), suggesting that the issue might be upstream in HTSLib.
3.  The other file doesn't have issues with samtools view.

```
$ samtools view HG00114.0025.cram chr8:145100000-145138636
[main_samview] retrieval of region "chr8:145100000-145138636" failed due to truncated file or corrupt BAM index file
```

**Comment by ihaque-freenome** [comment] 2018-01-24 18:21
@kyleabeauchamp what version of samtools are you using? I can't reproduce the problem with samtools 1.3.1 or 1.5:

1.5
```
ihaque@frontend001:/tmp/ihaque/1kg$ samtools --version
samtools 1.5
Using htslib 1.5
Copyright (C) 2017 Genome Research Ltd.
ihaque@frontend001:/tmp/ihaque/1kg$ samtools view HG00114.0025.cram chr8:145100000-145138636
ihaque@frontend001:/tmp/ihaque/1kg$ 
```
1.3.1
```
ihaque@frontend001:/tmp/ihaque/1kg$ /static/tools/samtools-1.3.1/bin/samtools --version
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.
ihaque@frontend001:/tmp/ihaque/1kg$ /static/tools/samtools-1.3.1/bin/samtools view HG00114.0025.cram chr8:145100000-145138636
ihaque@frontend001:/tmp/ihaque/1kg$ 
```

**Comment by kyleabeauchamp** [comment] 2018-01-24 18:22
```
samtools --version
samtools 1.6
Using htslib 1.6
Copyright (C) 2017 Genome Research Ltd.
```

**Comment by kyleabeauchamp** [comment] 2018-01-24 18:33
So pysam 0.13 is based off HTSLib 1.6

**Comment by daviesrob** [comment] 2018-01-25 15:34
@ihaque-freenome Thanks for the pass and fail cases, very useful.  See pull request samtools/htslib#653.  I'll need @jkbonfield to take a look over it before merging, as he's the expert in this area.

In both your tests, it looks like the requested region was after the last read on the chromosome, so the correct result is to return no reads.  In both cases the index caused reading to start at the file location just after all of the chr8 data.  What's then supposed to happen is that `cram_next_slice()` reads a container header, discovers it is for a location beyond the requested range and so sets `fd->eof = 1` and exits.

For the failure case (HG00114.0025.cram) what actually happened was that it skipped over lots of containers due to a missing check at [cram_decode.c line 2944](https://github.com/samtools/htslib/blob/1c5c5089/cram/cram_decode.c#L2944) until it hit one for chromosome X.  That had an end position high enough to terminate the loop.  The check at [line 2954](https://github.com/samtools/htslib/blob/1c5c5089/cram/cram_decode.c#L2954) then caused the function to exit, but without setting the `eof` flag.  This was then interpreted as an error.

For the pass case (HG00114.0005.cram) the same container skipping process happened, but for that one it ended when it reached a container with reads for more than one reference in it.  These use the special reference id -2, which allowed it to pass the test at [line 2954](https://github.com/samtools/htslib/blob/1c5c5089/cram/cram_decode.c#L2954).  The end of the region is then detected much later (probably around [line 3200](https://github.com/samtools/htslib/blob/1c5c5089/cram/cram_decode.c#L3200)) and in this case correctly flagged by setting `fd->eof = 1`.

**Comment by kyleabeauchamp** [comment] 2018-01-27 18:26
Thanks @daviesrob, I can confirm the upstream samtools 1.7 works, so we should be good once pysam is upgraded.

**Comment by AndreasHeger** [comment] 2018-02-07 20:43
Thanks all, the example is now working on the master branch after the upgrade to htslib 1.7.
Closing this issue.

**Closed by AndreasHeger** 2018-02-07 20:43 UTC
Labels: SAM/BAM/CRAM, upstream
