### ISSUE TITLE
Segmentation fault in samtools_test.StdoutTest

### ISSUE THREAD

**Issue by tillea** [pysam-developers/pysam#542] opened 2017-09-18 20:45 UTC
Hi,
thanks for your help to get the test suite working.  Unfortunately I'm running into another problem:

    testUsage (samtools_test.SamtoolsTest) ... SKIP: skipping usage tests, stdin is not a tty
    testDoubleCalling (samtools_test.StdoutTest) ... Segmentation fault
    E: pybuild pybuild:283: test: plugin distutils failed with: exit code=139: cd /build/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose 

Is there any chance to enhance the output for more detailed debugging output?
Kind regards, Andreas.

**Comment by tillea** [comment] 2017-09-25 17:44
Hi,
I switched from nosetest to pytest and got some more informative error message:

    =================================== FAILURES ===================================
    _____________________________ TestIO.testCRAM2CRAM _____________________________
    
    self = <AlignmentFile_test.TestIO testMethod=testCRAM2CRAM>
    
        def testCRAM2CRAM(self):
            self.checkEcho("ex2.cram",
                           "ex2.cram",
                           "tmp_ex2.cram",
                           "rc", "wc",
                           sequence_filename=os.path.join(BAM_DATADIR, "ex1.fa"),
    >                      checkf=check_samtools_view_equal)
    
    tests/AlignmentFile_test.py:530: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    tests/AlignmentFile_test.py:501: in checkEcho
        output_filename))
    E   AssertionError: files ex2.cram and tmp_ex2.cram are not the same
    =============================== warnings summary ===============================
    .pybuild/pythonX.Y_2.7/build/tests/AlignmentFile_test.py::TestTruncatedBAM::testTruncatedBam2
      /build/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build/tests/AlignmentFile_test.py:1864: UserWarning: no BGZF EOF marker; file may be truncated
        ignore_truncation=True)
    
    -- Docs: http://doc.pytest.org/en/latest/warnings.html
    ======== 1 failed, 768 passed, 10 skipped, 1 warnings in 62.85 seconds =========
    E: pybuild pybuild:283: test: plugin distutils failed with: exit code=1: cd /build/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build; python2.7 -m pytest tests

I wanted to check the difference between the files ex2.cram and tmp_ex2.cram but the latter does not exist at all.
If you need any more detailed information to track down the issue just let me know how to obtain it.
Kind regards, Andreas.

**Comment by 0xaf1f** [comment] 2017-09-30 20:49
@tillea, can you retitle this ticket to reflect the actual problem discovered after switching to pytest? I think @AndreasHeger thinks this issue still refers to the test configuration problem (from checking email subject lines and prioritizing messages to read).

**Comment by AndreasHeger** [comment] 2017-10-02 12:18
Thanks @0xaf1f and @tillea. I have trouble reproducing it. The test passes locally:
```
cd tests
  python AlignmentFile_test.py -v TestIO.testCRAM2CRAM
building data files
make: Entering directory `/ifs/devel/andreas/pysam/tests/pysam_data'
make: Nothing to be done for `all'.
make: Leaving directory `/ifs/devel/andreas/pysam/tests/pysam_data'
starting tests
testCRAM2CRAM (__main__.TestIO) ... ok

----------------------------------------------------------------------
Ran 1 test in 1.041s

OK
```
It also works through pytests.
Does tests/pysam_data/ex2.cram exist?

**Comment by 0xaf1f** [comment] 2017-10-07 03:34
Strange. The test works with the package as installed, but fails during the build. tests/pysam_data/ex2.cram does indeed exist.

```
(unstable-amd64-sbuild)root@workstation:/build/python-pysam-oXK81P/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build/tests# ls -l tmp_ex2.cram pysam_data/ex2.cram
-rw-rw-r-- 1 afif afif 58116 Oct  7 03:20 pysam_data/ex2.cram
-rw-rw-r-- 1 root root 58137 Oct  7 03:25 tmp_ex2.cram
```

I'm attaching them here. I haven't really used cram files before to know how to inspect them offhand.

[cram2cram-test.tar.gz](https://github.com/pysam-developers/pysam/files/1364281/cram2cram-test.tar.gz)

**Comment by AndreasHeger** [comment] 2017-12-08 17:09
Thanks, sorry for being slow on this. From their content, both files are the same apart from their header:
```
samtools view -h -T ../tests/pysam_data/ex1.fa ex2.cram > a
samtools view -h -T ../tests/pysam_data/ex1.fa tmp_ex2.cram > b
diff a b
1,2c1,2
< @SQ   SN:chr1 LN:1575 M5:426e31835a6dfdcbf6c534671edf02f7     UR:/build/python-pysam-oXK81P/python-pysam-0.12.0.1+ds/tests/pysam_data/ex1.fa
< @SQ   SN:chr2 LN:1584 M5:b6853ffe730ece50076db834dea18e3b     UR:/build/python-pysam-oXK81P/python-pysam-0.12.0.1+ds/tests/pysam_data/ex1.fa
---
> @SQ   SN:chr1 LN:1575 M5:426e31835a6dfdcbf6c534671edf02f7     UR:/build/python-pysam-oXK81P/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build/tests/pysam_data/ex1.fa
> @SQ   SN:chr2 LN:1584 M5:b6853ffe730ece50076db834dea18e3b     UR:/build/python-pysam-oXK81P/python-pysam-0.12.0.1+ds/.pybuild/pythonX.Y_2.7/build/tests/pysam_data/ex1.fa
```
It seems that in your build different reference sequences are used causing the the header to be different and the test to fail.
I have now set the option in the test
```
without_header=True
```
maybe this will make it better?

**Comment by tillea** [comment] 2017-12-08 19:42
Hi Andreas,

On Fri, Dec 08, 2017 at 05:09:51PM +0000, Andreas Heger wrote:
> It seems that in your build different reference sequences are used causing the the header to be different and the test to fail.
> I have now set the option in the test
> ```
> without_header=True
> ```
> maybe this will make it better?

I admit I need to refresh my mind about this.  If I understand correctly for the next pysam release we can drop this patch
   https://anonscm.debian.org/cgit/debian-med/python-pysam.git/tree/debian/patches/rename-helper-function-to-prevent-it-from-being-picked-up-by-nose.patch
right?
Thanks for keeping me updated with the issue, Andreas.

**Comment by AndreasHeger** [comment] 2017-12-15 13:17
Thanks, not sure, the link seems to be broken. I think the issue might be that you run tests from a different location than I and travis do, and the tests were not robust enough for this. I have tried running all tests now from outside the repo and that seems to work now (with pytest)

I am closing the issue now, please reopen if still an issue.

**Closed by AndreasHeger** 2017-12-15 13:17 UTC
Labels: SAM/BAM/CRAM
