### ISSUE TITLE
Pysam hangs on remote BAM fetch when server doesn't implement byte serving

### ISSUE THREAD

**Issue by dcolligan** [pysam-developers/pysam#107] opened 2015-04-14 15:55 UTC
Opening a remote BAM file causes pysam to hang when the BAM file is being served by a server that doesn't support byte serving.

To reproduce, run a server that doesn't implement byte serving in one terminal:
```
$ ls
HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai
$ python -m SimpleHTTPServer 8080
Serving HTTP on 0.0.0.0 port 8080 ...
```
And in another terminal, try and fetch the file:
```
>>> import pysam
>>> a = 'http://localhost:8080/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam'
>>> b = pysam.AlignmentFile(a)
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
```
The pysam call will not return.

**Comment by AndreasHeger** [comment] 2015-04-15 19:59
Thanks. I expect this to be a htslib issue - does samtools have the same limitation?

Best wishes,
Andreas

**Comment by dcolligan** [comment] 2015-04-15 22:55
I'm not sure what code paths in samtools would trigger it, but AFAICT it looks like a pysam-only problem.  Here is a session using the same file served by the same non-byte-serving server:
```
$ samtools --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
$ samtools view http://localhost:8002/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam > view.txt
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.version.__version__
'0.8.2.1'
>>> a = 'http://localhost:8002/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam'
>>> b = pysam.AlignmentFile(a)
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
... hangs ...
```
If I am trying to reproduce it the wrong way, please let me know.

**Comment by AndreasHeger** [comment] 2015-04-16 08:52
Thanks, I will take a look. Best, andreas                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the EE network.                                                                                                                                                                                                                From: Danny ColliganSent: Wednesday, 15 April 2015 23:56To: pysam-developers/pysamReply To: pysam-developers/pysamCc: Andreas HegerSubject: Re: [pysam] Pysam hangs on remote BAM fetch when server doesn't implement byte serving (#107)I'm not sure what code paths in samtools would trigger it, but AFAICT it looks like a pysam-only problem.  Here is a session using the same file served by the same non-byte-serving server:

$ samtools --version
samtools 1.2
Using htslib 1.2.1
Copyright (C) 2015 Genome Research Ltd.
$ samtools view http://localhost:8002/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam > view.txt
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.version.__version__
'0.8.2.1'
>>> a = 'http://localhost:8002/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam'
>>> b = pysam.AlignmentFile(a)
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
... hangs ...


If I am trying to reproduce it the wrong way, please let me know.

—Reply to this email directly or view it on GitHub.

**Comment by AndreasHeger** [comment] 2015-04-16 20:39
Hi,  I just tried and it seems to work for me:

```
rm -f *; python -c "import pysam; a = pysam.AlignmentFile('http://0.0.0.0:8090/pysam_ex1.bam'); print a.fetch().next()"
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
[M::test_and_fetch] downloading file 'http://0.0.0.0:8090/pysam_ex1.bam.bai' to local directory
EAS56_57:6:190:289:82   69      0       99      0       None    0       99      35      CTCAAGGTTGTTGCAAGGGGGTCTATGTGAACAAA     array('B', [27, 27, 27, 22, 27, 27, 27, 26, 27, 27, 27, 27, 27, 27, 27, 27, 23, 26, 26, 27, 22, 26, 19, 27, 26, 27, 26, 26, 26, 26, 26, 24, 19, 27, 26])  [('MF', 192)]
```
Any ideas? 

pysam is a fairly thin wrapper around htslib calls and does no communication handling on its own, so I would be suprised if this is a pysam issue - unless there is some parameterization that is different between calls in pysam and samtools.

Best wishes,
Andreas

**Comment by dcolligan** [comment] 2015-04-17 20:44
I agree that, logically, it is strange that I'm finding this bug in pysam and not in samtools.  But that's what seems to be happening.

The bug has something to do with the size of the files, I think:
```
$ du -hs *
 89M	HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam
5.0M	HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai
4.0K	wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam
4.0K	wgEncodeUwRepliSeqBg02esG1bAlnRep1_sample.bam.bai
```

When I try to fetch the 89M file with pysam, it hangs, but when I try to fetch the 4K file, it does not.  Samtools view works with both files.  Perhaps see if you can replicate the bug with a larger BAM/BAI file?

**Comment by AndreasHeger** [comment] 2015-04-17 21:11
Thanks for the suggestion, will try!

**Comment by AndreasHeger** [comment] 2015-04-21 20:52
Thanks, the file size is indeed the deciding factor.

It hangs at:

```
open("mC-foetal-dex-R1.bwa.bam.csi", O_RDONLY) = -1 ENOENT (No such file or directory)
brk(0x1a6c000)                          = 0x1a6c000
socket(PF_NETLINK, SOCK_RAW, 0)         = 4
bind(4, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
getsockname(4, {sa_family=AF_NETLINK, pid=59751, groups=00000000}, [12]) = 0
sendto(4, "\24\0\0\0\26\0\1\3\23\2706U\0\0\0\0\0\0\0\0", 20, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 20
recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"0\0\0\0\24\0\2\0\23\2706Ug\351\0\0\2\10\200\376\1\0\0\0\10\0\1\0\177\0\0\1"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 168
recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"@\0\0\0\24\0\2\0\23\2706Ug\351\0\0\n\200\200\376\1\0\0\0\24\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 192
recvmsg(4, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0\23\2706Ug\351\0\0\0\0\0\0\1\0\0\0\24\0\1\0\0\0\0\0"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
close(4)                                = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(4, SOL_SOCKET, SO_LINGER, {onoff=0, linger=0}, 8) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(8083), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
write(4, "GET /mC-foetal-dex-R1.bwa.bam.cs"..., 78) = 78
read(4, 
```

**Comment by AndreasHeger** [comment] 2015-04-25 20:38
Hi @dcolligan,  after some testing it does seem to be a htslib issue related to opening an index. The following works:
```
samtools view http://0.0.0.0:8083/mC-foetal-dex-R1.bwa.bam
...
```
while the following hangs:
```
samtools view http://0.0.0.0:8083/mC-foetal-dex-R1.bwa.bam chr1
[knet_seek] SEEK_END is not supported for HTTP. Offset is unchanged.
```
It seems that opening the bam-file for random access causes the stalling. Unfortunately, pysam always attempts to open an index. I'd be grateful if you could confirm that - I will then open an issue in htslib.

Best wishes,
Andreas

**Comment by jmarshall** [comment] 2015-04-27 15:23
This hang is because `python -m SimpleHTTPServer` handles only one connection at a time.

The client establishes a connection to GET the BAM file, and then establishes another connection to GET the index.  The blocked `read(4,` will return if the first connection finishes and SimpleHTTPServer gets to the pending request — but of course that never happens.

If one cared to support single-connection web servers, one could read the index before establishing the connection for the BAM file.  This would require a lot of reorganisation for samtools so I don't propose to fix this there.  Pysam could I suppose rearrange the file opening in _calignmentfile.pyx_'s `_open`, but I'm not sure I would recommend it!

**Comment by dcolligan** [comment] 2015-04-27 17:20
@AndreasHeger Yes, I can confirm that adding the `chr1` reference makes a samtools remote BAM fetch hang whereas a remote fetch without a `chr1` does not.

Note, however, that this only applies to files over a certain size (the BAM/BAI I used were 89M/5M).  Smaller files are fetched successfully with or without the reference (4K/4K).

**Comment by AndreasHeger** [comment] 2015-04-27 20:37
Thanks, jmarshall and @dcolligan, that is very helpful. Fixing this seems beyond pysam (and my expertise). Out of curiosity, why do small bam files work, but not large files?

Best, Andreas

**Comment by jmarshall** [comment] 2015-04-28 06:18
Small files fit in the server host's transmit buffer, so SimpleHTTPServer is able to send the whole BAM file and close its end of the BAM file connection, and then is available to process the pending index file connection.

**Comment by AndreasHeger** [comment] 2015-04-29 08:58
Thanks! I am closing this issue.

**Closed by AndreasHeger** 2015-04-29 08:58 UTC

**Comment by dcolligan** [comment] 2015-04-29 17:13
@AndreasHeger if you filed an issue in another repo originating out of this issue, can you link it here, just for reference?

**Comment by AndreasHeger** [comment] 2015-04-30 09:28
Hi @dcolligan, I did not file an issue. It seems that requiring multiple connections is a design choice in htslib. I can add some text to the pysam FAQ.

Best wishes,
Andreas
