### ISSUE TITLE
Issue Installing Pysam on Ubuntu machine

### ISSUE THREAD

**Issue by Shruteek** [pysam-developers/pysam#1202] opened 2023-06-30 07:02 UTC
I am trying to install pysam on a Ubuntu virtual machine. I have Python 3.11 (latest) and am attempting to install pysam in a miniconda environment, specifically running the command:
`conda install pysam -c bioconda -n sgRNA`
To install pysam via bioconda. When I do this, the initial and flexible solver fails, with the following error message: 
![temp](https://github.com/pysam-developers/pysam/assets/45547058/f8d9ca12-8e70-4246-9789-043b806a6257)

**Comment by jmarshall** [comment] 2023-06-30 08:38
Bioconda does not yet make Python 3.11 builds, which is a bioconda issue that has nothing to do with pysam. See https://github.com/bioconda/bioconda-recipes/issues/37805.

If you want to use pysam with Python 3.11, you should install via `pip` or build it yourself.

(Duplicate of #1191.)

**Closed by jmarshall** 2023-06-30 08:38 UTC

**Comment by Shruteek** [comment] 2023-06-30 19:44
Thank you so much, @jmarshall - I used pip instead, and it worked! You just saved me a lot of trouble!

**Comment by jmarshall** [comment] 2024-06-25 04:27
As of this month, bioconda now provides pysam for Python 3.11 and 3.12. See https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2169605103.
