### ISSUE TITLE
typedef redefinition when using system-installed htslib

### ISSUE THREAD

**Issue by nieder** [pysam-developers/pysam#420] opened 2017-03-20 10:56 UTC
I'm building pysam-0.10.0 using my system-installed htslib-1.4 (using HTSLIB_INCLUDE_DIR & HTSLIB_LIBRARY_DIR). The build fails with this error:

~~~~
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I/sw/include -Isamtools -Ibcftools -Ipysam -I. -I/sw/include -I/sw/include/python2.7 -c samtools/bam2bcf.c.pysam.c -o build/temp.macosx-10.11-x86_64-2.7/samtools/bam2bcf.c.pysam.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
In file included from samtools/bam2bcf.c.pysam.c:37:
In file included from samtools/bam2bcf.h:31:
samtools/errmod.h:36:3: error: typedef redefinition with different types ('struct errmod_t'
      (aka 'errmod_t') vs 'struct errmod_t')
} errmod_t;
  ^
/sw/include/htslib/hts.h:659:25: note: previous definition is here
typedef struct errmod_t errmod_t;
                        ^
1 error generated.
error: command 'gcc' failed with exit status 1
~~~~

OS X 10.11

**Comment by bioinformed** [comment] 2017-03-20 17:15
Quick answer-- `pysam` doesn't yet support `htslib 1.4`.  We are working to correct this fairly quickly.

**Comment by AndreasHeger** [comment] 2017-04-08 19:46
Thanks, duplicate of #413 , closing this thread

**Closed by AndreasHeger** 2017-04-08 19:46 UTC
Labels: duplicate
