### ISSUE TITLE
Exiting after failing commands is pretty unacceptable

### ISSUE THREAD

**Issue by gregmcinnes** [pysam-developers/pysam#965] opened 2020-11-03 19:10 UTC
I was excited to find this library but I don't think I can use it and feel confident running it at any sort of scale.  It really needs to throw an error and report the error message if the underlying command fails.  Otherwise it's difficult to trust anything that's run with this library.  

I was contemplating creating a "success" file after the bcftools and running a separate script that checks for the success file, but that should not be necessary.

**Comment by leeleavitt** [comment] 2021-07-27 17:47
It can be painful to debug, but please be more empathetic when you write these issues down.

**Comment by jmarshall** [comment] 2021-08-23 11:54
Duplicate of #506

**Closed by jmarshall** 2021-08-23 11:54 UTC
