### ISSUE TITLE
pysam get_index_statistics produces incorrect values for cram 

### ISSUE THREAD

**Issue by arpanda** [pysam-developers/pysam#1067] opened 2021-12-20 20:44 UTC
Hi,
I was trying to get the index statistics result from a cram file using pysam's `get_index_statistics` function. Looks like its not working properly. This is probably due to `htslib` version. Here is the link for reported issue in `samtools`. https://github.com/samtools/samtools/issues/303

Python code.
```python
import pysam

cram_file = 'file1.cram'
crai_file= 'file1.cram.crai'
bam_obj = pysam.AlignmentFile(cram_file, 'rc', index_filename=crai_file)

for index_stat in bam_obj.get_index_statistics():
    print(index_stat)
```

this resulted the following outputs. Only few lines were shown. 
```
IndexStats(contig='chr1', mapped=0, unmapped=0, total=0)
IndexStats(contig='chr2', mapped=0, unmapped=0, total=0)
IndexStats(contig='chr3', mapped=0, unmapped=0, total=0)
IndexStats(contig='chr4', mapped=0, unmapped=0, total=0)
IndexStats(contig='chr5', mapped=0, unmapped=0, total=0)
IndexStats(contig='chr6', mapped=0, unmapped=0, total=0)
```

For the same cram file, here is the few lines of output for `samtools idxstats ` command. Which looks fine

```
chr1	248956422	84858569	508584
chr2	242193529	82787449	534025
chr3	198295559	68476796	412337
chr4	190214555	67335675	391402
chr5	181538259	61838396	370668
```
Probably, this is not solved in pysam yet. Any other view?

**Comment by jmarshall** [comment] 2021-12-20 23:15
Duplicate of #1060.

CRAI indexes do not contain this information, so it is returned as 0. This is now (since b6dffd326dfe9ac9edba345f59e46a4bdc3307aa) mentioned in [the documentation](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.get_index_statistics).

**Closed by jmarshall** 2021-12-20 23:15 UTC
