### ISSUE TITLE
Can't import pysam on python3

### ISSUE THREAD

**Issue by mshong0320** [pysam-developers/pysam#459] opened 2017-05-10 20:55 UTC
Hello everyone,

I'm trying to import pysam to python3 after installing it using pip3. 
However, I keep on getting the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7724)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so, 2): Library not loaded: @rpath/pysam-0.11.1-py3.6-macosx-10.6-intel.egg/pysam/libcsamtools.cpython-36m-darwin.so
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so
  Reason: image not found

Pysam works well on Python2, but the installation isn't working on python3. Does anyone know why I'm getting this installation error on python3? And anyone know a solution to this problem?

Thanks in advance.

**Comment by llz-hiv** [comment] 2017-05-11 06:35
Since you installed it by using pip3, You should type "python3 ./XX.py" instead of "python"

**Comment by mshong0320** [comment] 2017-05-11 18:04
llz-hiv: It's not a script I'm having difficulty running. This is a package I'm trying to import on Python3. 
If you try installing pysam with pip3 install pysam, then import pysam on python3, you'll see what I mean.

**Comment by bioinformed** [comment] 2017-05-11 18:14
I'm not able to reproduce this bug.  However, I've seen another report and
here is the workaround that was effective:

  * pip3 wheel pysam
  * pip3 install pysam*.whl

**Comment by mshong0320** [comment] 2017-05-11 18:49
Hi bioinformed:
Thanks so much! It worked. But now I'm curious to know why that worked. I've looked into the wheel package and what it does, but I guess I don't really understand well how a process of package installation works to understand why that wheel package solved the problem I've been having.

Would you mind explaining to me how the suggestion you gave me solved the issue I was having?

**Comment by bioinformed** [comment] 2017-05-11 18:56
I wish I understood why installing from wheel works as well.

The root cause involves how the relative shared library paths are set.
 pysam need relative shared library paths because the pysam code is used as
a module, but also as a library to link against by packages that build on
pysam.  Native Python doesn’t really address this use-case and it took some
fairly hairy surgery to the build system to get it to work at all.  The
magic is performed by the cy_build.py module, which sets linker flags and
tries to account for the slightly different install paths and processes
used by setuptools and pip.

Hope that helps...

**Comment by AndreasHeger** [comment] 2017-07-10 15:31
Closing this issue for now, osx linking still WIP.

**Closed by AndreasHeger** 2017-07-10 15:31 UTC

**Comment by brianpenghe** [comment] 2021-03-27 22:49
I see the same bug
