### ISSUE TITLE
pysam write appears to truncate files

### ISSUE THREAD

**Issue by mce1** [pysam-developers/pysam#509] opened 2017-07-20 19:23 UTC
Hi there,

I would like to split a very large bam file into subfiles, one for each chromosome and each with an appropriate header. Using pysam I have come up with the following:

```
#! /usr/bin/python

import pysam

PySam_test = pysam.AlignmentFile('test.bam')

chromosomes = zip(PySam_test.references, PySam_test.lengths)

def split_PySam_test_by_chromosome(chromosome):
    outfile = pysam.AlignmentFile("test_%s.bam" % chromosome[0], "wb", reference_names=[chromosome[0]], reference_lengths=[chromosome[1]])
    for alignment in PySam_test.fetch(reference=chromosome[0]): outfile.write(alignment)
    outfile.close()

map(split_PySam_test_by_chromosome, chromosomes)
```

Unfortunately, this seems to work for the first subfile only (i.e. test_chr1.bam). All the remaining files are written to disk and appear to have roughly the appropriate size, however, samtools view -h prints the header and then gives a truncated file error, e.g.: 

```
@SQ     SN:2    LN:242193529 
[main_samview] truncated file.
```

Looks as though the end of file is not indicated properly, but why does it work for the first file but not all the others when all of them are generated from the same loop?

Any help would be much appreciated.

Cheers,

mce

PS: In the end, I would like to make that run in paralell, i.e.

```
import multiprocessing
cpus = multiprocessing.cpu_count()

pool = multiprocessing.Pool(cpus)
pool.map(split_PySam_by_chromosome, chromosomes)
pool.close()
```
Hence the map statement.

**Comment by AndreasHeger** [comment] 2017-07-21 11:50
Thanks for reporting, I can reproduce this.

**Comment by AndreasHeger** [comment] 2017-07-21 12:05
The following works:
```
#! /usr/bin/python                                                                                                                                                                                                                           

import pysam

with pysam.AlignmentFile('pysam_data/ex1.bam') as inf:
    chromosomes = zip(inf.references, inf.lengths)

def split_PySam_test_by_chromosome(info):
    chromosome, length = info
    with pysam.AlignmentFile('pysam_data/ex1.bam') as inf:
        with pysam.AlignmentFile(
                "test_%s.bam" % chromosome,
                "wb",
                template=inf) as outf:
            for alignment in inf.fetch(reference=chromosome):
                outf.write(alignment)

list(map(split_PySam_test_by_chromosome, chromosomes))
```
The issue has been that you are writing reads to BAMs with different sequence dictionaries. When writing reads from one BAM file to another you need to ensure that the sequence dictionary is the same, i.e. the same chromosomes appear and in the same order. This is because in the BAM format the chromosome a reads maps to is a number (tid) that needs to be consistent. Alternatively, the following works:
```
#! /usr/bin/python                                                                                                                                                                                                                           

import pysam

with pysam.AlignmentFile('pysam_data/ex1.bam') as inf:
    chromosomes = zip(inf.references, inf.lengths)

def split_PySam_test_by_chromosome(info):
    chromosome, length = info
    with pysam.AlignmentFile('pysam_data/ex1.bam') as inf:
        with pysam.AlignmentFile(
                "test_%s.bam" % chromosome,
                "wb",
                reference_names=[chromosome],
                reference_lengths=[length]) as outf:
            for alignment in inf.fetch(reference=chromosome):
                alignment.tid = 0
                outf.write(alignment)

list(map(split_PySam_test_by_chromosome, chromosomes))
```
As you can see, that is a bit cumbersome.
Unfortunately, as the header is written at the top of a BAM file, it is the header that determines how tids map to chromosome names, and not vice versa.

Please note also when multiprocessing that you can not use an already opened AlignmentFile object.

**Comment by mce1** [comment] 2017-07-23 19:43
Hi Andreas,

thanks a lot for the prompt reply!

While the first solution works fine I don't seem to be able to get the second one to work. Instead, for several bam files I have tested, I get the same result as before: The first subfile looks fine but all the others give a truncated file error. Is there maybe something else you need to change apart from tid/reference_id? Can your test file `pysam_data/ex1.bam` be downloaded somewhere so I can check for differences?

Thanks a  lot,

mce

**Comment by AndreasHeger** [comment] 2017-07-24 14:29
Hi, the ex1.bam file is part of the repository (https://github.com/pysam-developers/pysam/blob/master/tests/pysam_data/ex1.sam.gz) but needs to be converted to BAM first.

**Comment by mce1** [comment] 2017-07-24 15:20
When I try 

`samtools view -b -o ex1.bam ex1.sam`

I get
```
[E::sam_parse1] missing SAM header
[W::sam_read1] parse error at line 1
[main_samview] truncated file.
```

Seems this file doesn't have a header at all?

**Comment by daveuu** [comment] 2017-09-01 18:25
I am also having this issue, but I need to update the header in the new file to list only one sequence, not the several sequences in the original BAM file (because a third party program is creating a consensus sequence and seems to use the header for the length i.e., tries to create consensus from a concatenation of all of the SQs listed in header but reads for only one are retained in the generated single SQ file . . .).

And I also cannot get the second proposed solution from @AndreasHeger to work. That is, re-assigning the .tid attribute integer to 0 (which is [deprecated](http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.tid): but using .reference_id also fails).

I'm wondering whether the second solution was actually tested, given that `ex1.bam` has no header (as pointed out by @mce1) and if it doesn't work, is there a bug in that reassigning `reference_id` on a `pysam.AlignedSegment` does not work?

I tried writing the `AlignedSegment` instances with `.reference_id` set to 0 into a SAM file with a header containing one sequence like this:
```
@HD     VN:1.3  SO:coordinate
@SQ     SN:NS   LN:890
@PG     PN:bwa  ID:bwa  ...
```

and ended up with entries like this:

`MISEQ:179:000000000-AM909:1:1101:13633:3115     99      <A3><B1>        1       60      150M    =
       207     356     AGCGAAAGCAGG ....`

It seems `<A3><B1>` should be `NS`? Parsing this SAM file with pysam caused the python process to crash (Segmentation fault).

**Comment by daveuu** [comment] 2017-09-04 10:18
OK! While making a reproducible example of the above issue, it did in fact work (so I'll go and have a closer look at my other code). In the meantime, this might help others trying to do the same thing (works since at least 0.9.1.4):
```python
#!/usr/bin/env python
import subprocess
import os
import pysam

print("\ntesting pysam's ability to separate reads into SAM files according "\
        "to mapped reference while creating new header files with only "\
        "included reference sequence per file\n")

print('pysam version:',pysam.__version__)

# make a simple SAM file to test with
f = open("foo.sam", "w")
f.write("@HD\tVN:1.5\tSO:coordinate\n")
f.write("@SQ\tSN:chrA\tLN:1000\n")
f.write("@SQ\tSN:chrB\tLN:1000\n")
f.write('\t'.join(["read1","2","chrA","1","60","10M","*","0","0",
        "AGCAAAAGCA","BCCCCFFFFF\n"]))
f.write('\t'.join(["read2","2","chrB","1","60","10M","*","0","0",
        "GAGCAAAAGC","AB@?ABFFB4"]))
f.close()

# BAM and index it so we can fetch reads per chromosome (reference sequence)
pysam.view("-b", "-h", "-o", "foo.bam", "foo.sam", catch_stdout = False)
pysam.index("foo.bam")

bam_in = pysam.AlignmentFile("foo.bam")

print('Header dict of 2 reference seq sam file')
print(bam_in.header)

with pysam.AlignmentFile("bar.bam", "wb", header = bam_in.header) as bam_out:
    for read in bam_in.fetch('chrA'):
        print('reference_id of read on chrA in bar.bam',read.reference_id)
        bam_out.write(read)
    for read in bam_in.fetch('chrB'):
        print('reference_id of read on chrB in bar.bam',read.reference_id)
        bam_out.write(read)

### make a BAM with just chrA and its read
# make a header with just the chrA reference
chrA_header = {}
for k,v in bam_in.header.items():
    if k == 'SQ':
        chrA_header[k] = [v[0]]
    else:
        chrA_header[k] = v

with pysam.AlignmentFile("bar_chrA.bam", "wb", header = chrA_header) as bam_out:
    for read in bam_in.fetch('chrA'):
        print('reference_id of read on chrA in bar_chrA.bam',read.reference_id)
        bam_out.write(read)
    print('Finished writing to bar_chrA.bam, about to close . . .')

pysam.index("bar_chrA.bam")

### make a BAM with just chrB and its read
# make a header with just the chrB reference
chrB_header = {}
for k,v in bam_in.header.items():
    if k == 'SQ':
        chrB_header[k] = [v[1]]
    else:
        chrB_header[k] = v

with pysam.AlignmentFile("bar_chrB.bam", "wb", header = chrB_header) as bam_out:
    for read in bam_in.fetch('chrB'):
        # without the next line . . .
        # if writing to a BAM, no reads recovered below
        # if writing to a SAM, Segmentation fault (when "with" line above is in mode "w")
        read.reference_id = 0
        print('reference_id of read on chrB in bar_chrB.sam',read.reference_id)
        bam_out.write(read)
    print('Finished writing to bar_chrB.bam, about to close . . .')

pysam.index("bar_chrB.bam")

with pysam.AlignmentFile("bar_chrA.bam", "rb") as aln_in:
    print('Header for bar_chrA.bam:')
    print(aln_in.header)
    for read in aln_in.fetch('chrA'):
        print('reference_id of read on chrA in bar_chrA.bam',read.reference_id)

with pysam.AlignmentFile("bar_chrB.bam", "rb") as aln_in:
    print('Header for bar_chrB.bam:')
    print(aln_in.header)
    for read in aln_in.fetch('chrB'):
        print('reference_id of read on chrB in bar_chrB.bam',read.reference_id)

print('All done.')
```

**Comment by daveuu** [comment] 2017-09-04 13:48
Well . . . when using the code above with real data, I still get a segmentation fault if writing to SAM and an apparently invalid header if writing to BAM (which SamTools calls a truncated file). So I can't reproduce it in a simple way . . . but I think there is still a bug somewhere in there concerning reassignment of `reference_id` attribute of AlignedSegments when transferring from one AlignmentFile to another. :-(

**Comment by daveuu** [comment] 2017-09-04 14:52
This can reproduce the problem. It turns out to be related to paired read information being present or not.
```python
#!/usr/bin/env python
import subprocess
import os
import pysam

##### pySAM cannot use new AlignmentFile headers when paired read information is
##### present in a multi reference input file. This script splits an input SAM
##### containing reads mapped to each of two references into two separate
##### SAM files each with appropriate headers i.e., just the reference for which
##### those reads are mapped, but . . .

### . . . fails:
## with paired read mapped info
pair_status = ['=',"1","60"]
# New single reference header for a single reference AlignmentFile
use_single_header = True

### . . . succeeds:
## with paired read mapped info
#pair_status = ['=',"1","60"]
## Original multi-reference header for a single reference AlignmentFile
#use_single_header = False

### . . . succeeds:
## without paired read mapped info
#pair_status = ['*',"0","0"]
## New single reference header for a single reference AlignmentFile
#use_single_header = False

print('pysam version:',pysam.__version__)

# make a simple SAM file to test with
f = open("foo.sam", "w")
f.write("@HD\tVN:1.5\tSO:coordinate\n")
f.write("@SQ\tSN:chrA\tLN:1000\n")
f.write("@SQ\tSN:chrB\tLN:1000\n")
f.write('\t'.join(["read1","2","chrA","1","60","10M"] + pair_status + \
        ["GAGCAAAAGC","AB@?ABFFB4\n"]))
f.write('\t'.join(["read2","2","chrB","1","60","10M"] + pair_status + \
        ["GAGCAAAAGC","AB@?ABFFB4"]))
f.close()

# BAM and index it so we can fetch reads per chromosome (reference sequence)
pysam.view("-b", "-h", "-o", "foo.bam", "foo.sam", catch_stdout = False)
pysam.index("foo.bam")

bam_in = pysam.AlignmentFile("foo.bam")
print('Header dict of 2 reference seq sam file')
print(bam_in.header)

## make new SAM files with just one or other reference and its reads
# optionally make a header with just the included reference (determined
# by use_single_header)
for n,C in enumerate('AB'):
    if use_single_header:
        new_header = {}
        for k,v in bam_in.header.items():
            if k == 'SQ':
                new_header[k] = [v[n]]
            else:
                new_header[k] = v
        use_header = new_header
    else:
        use_header = bam_in.header
    
    print('Header for chr'+C, use_header)

    with pysam.AlignmentFile("bar_chr{}.sam".format(C), "w", header = use_header,
            add_sam_header = True) as sam_out:
        for read in bam_in.fetch('chr'+C):
            print('reference_id of read on chr{0} in bar_chr{0}.sam'.format(C), 
                    read.reference_id)
            read.reference_id = 0
            sam_out.write(read)
        print('Finished writing to {}, about to close . . .'.format(
                sam_out.filename.decode('utf-8')))
    
    pysam.view("-b", "-h", "-o", "bar_chr{0}.bam".format(C), "bar_chr{0}.sam".format(C), 
            catch_stdout = False)
    pysam.index("bar_chr{}.bam".format(C))

print('All done.')
```

**Comment by AndreasHeger** [comment] 2017-09-05 22:19
Thanks, will take a look

**Comment by AndreasHeger** [comment] 2017-09-05 22:22
but just to be sure, if you have paired reads, both reference_id and next_reference_id need to be updated.

**Comment by daveuu** [comment] 2017-09-06 15:06
Yes :-)
```
...
            read.reference_id = 0
            read.next_reference_id = 0
            sam_out.write(read)
...
```
and it works. Thanks.

**Comment by AndreasHeger** [comment] 2017-11-10 14:34
Closing this now.

**Closed by AndreasHeger** 2017-11-10 14:34 UTC
