### ISSUE TITLE
Printing and floating precision from a VariantFile record

### ISSUE THREAD

**Issue by mattions** [pysam-developers/pysam#174] opened 2015-10-16 09:45 UTC
Hello there,

`pysam.VariantFile` is very good and pretty fast. We are checking if we can use it as a way to parse VCF faster.

I found a strange behaviour:

Consider this variant:

```
2       105115  .       G       A       93.5955 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5;CIGAR=1X;DP=6;DP4=0,0,3,2;DPB=6;DPRA=0;EPP=3.44459;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=11.5366;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=132;QR=0;RO=0;RPL=0;RPP=13.8677;RPPR=0;RPR=5;RUN=1;SAF=3;SAP=3.44459;SAR=2;SRF=0;SRP=0;SRR=0;TYPE=snp  GT      1/1
```

if I take just the quality from the code I get a different number:

```
In [15]: print variant.qual
93.5954971313
```

instead of
```
93.5955 
```

but, if I try to print the whole variant, I do get the float formatted as it was inserted.
This happens not only to the qual float, but also to all the other float which have not a clear precision:

This is the result:
```
2	105115	.	G	A	93.5954971313	.	AB=0.0;ABP=0.0;AC=2;AF=1.0;AN=2;AO=5;CIGAR=1X;DP=6;DP4=0,0,3,2;DPB=6.0;DPRA=0.0;EPP=3.44459009171;EPPR=0.0;GTI=0;LEN=1;MEANALT=2.0;MQM=60.0;MQMR=0.0;NS=1;NUMALT=1;ODDS=11.5366001129;PAIRED=1.0;PAIREDR=0.0;PAO=0.0;PQA=0.0;PQR=0.0;PRO=0.0;QA=132;QR=0;RO=0;RPL=0.0;RPP=13.8676996231;RPPR=0.0;RPR=5.0;RUN=1;SAF=3;SAP=3.44459009171;SAR=2;SRF=0;SRP=0.0;SRR=0;TYPE=snp	GT	1/1
```

Is there a way to have the value as inserted, with the right way of rounding?

**Comment by marcelm** [comment] 2015-10-20 09:46
I cannot help so much because I don’t know anything about the code, but perhaps it helps to know that 93.5954971313 is the single-precision (32-bit) representation of 93.5955. Perhaps the C 'float' type is used somewhere instead of the full-precision 'double' type.

**Comment by TyberiusPrime** [comment] 2015-10-20 10:16
The VCF spec says: "Floats are encoded as single-precision (32 bit) in the basic format defined by the IEEE-754-1985 standard."

So this behavior is just as it should.

**Comment by mattions** [comment] 2015-10-20 10:28
yes, but when I print the variant I get 93.5955. So I can go from the 93.5954971313 to 93.5955 for the quality, and do that also for all the other floats in the info field?

**Comment by marcelm** [comment] 2015-10-20 11:11
The sentence about floats being single-precision is from the BCF subsection. @mattions, perhaps you should clarify whether you are parsing VCF or BCF. Inaccurate round-tripping is still a bug, no matter which format.

**Comment by marcelm** [comment] 2015-10-20 11:16
To clarify: Having `variant.qual` print out 93.5954971313 is not a bug, that’s how finite precision floating point numbers work, but if you read a VCF, modify a record, print it out again and the floating point values you have touched look different, then that is a bug.

**Comment by TyberiusPrime** [comment] 2015-10-20 11:20
It also defines VCF and BCF as being equivalent - ie. if you express a number at greater precision in a VCF, BCF is not required to honor it - and arguably the bug is in your file.

I do not consider this inaccurate round-tripping.
The spec says that in BCF this field is only 32 bit wide. BCF and VCF are equivalent. Either string representation leads to the same 32bit floating point value.

**Comment by jmarshall** [comment] 2015-10-20 11:22
When you print the whole variant, pysam is calling htslib's `vcf_format` which formats the QUAL column with C's `sprintf("%g")`.

When you use `print variant.qual`, you're getting Python's default floating point formatting, which is probably fairly raw.  To compare like with like and display this same value with similar formatting and precision, you will want to format it yourself with whatever Python's equivalent of `%g` is.

**Comment by TyberiusPrime** [comment] 2015-10-20 11:27
Python's equivalent of "%g" is "%g" % your_float.

**Comment by marcelm** [comment] 2015-10-20 11:40
> It also defines VCF and BCF as being equivalent - ie. if you express a number at greater precision in a VCF, BCF is not required to honor it

The sentence about equivalence is in the BCF section of the spec, it would be surprising if this was a statement of what is allowed in a VCF.

> I do not consider this inaccurate round-tripping.

I agree for BCF/VCF/BCF roundtripping, but I meant VCF/VCF roundtripping.

I just want my diffs to work when I modify some records in a VCF file ...

**Comment by mp15** [comment] 2015-10-20 12:31
The only way to do what you want @marcelm would be to rewrite the standard to represent these numbers as fixed decimals. Whilst this is supported on a chip level in modern processors, it is not very well standardised at compiler level yet. gcc supports the _Decimal types from the technical report http://www.open-std.org/jtc1/sc22/open/n4060.pdf but clang does not yet (as of version 3.8).

It might be easier to standardise on a significant figure/rounding standard for BCF to VCF conversion?

**Comment by mattions** [comment] 2015-10-20 12:59
@jmarshall thanks for clarifying.
If I call
```
"{:0g}".format(variant.qual)
```
I get the expected formatting (93.5955).

Now that I know, I can do the same action when I print the values out.

For me this issue can be closed, thanks.

**Comment by AndreasHeger** [comment] 2016-02-20 20:13
Thanks, closing!

**Closed by AndreasHeger** 2016-02-20 20:13 UTC
