### ISSUE TITLE
dynamic module does not define init function (initlibchtslib)

### ISSUE THREAD

**Issue by bagavi** [pysam-developers/pysam#364] opened 2016-10-27 00:06 UTC
I am using version "(0.9.1.4)" on a Linux machine and I get the following error.

/usr/local/lib/python2.7/dist-packages/pysam/__init__.py in <module>()
      3 import sysconfig
      4 
----> 5 from pysam.libchtslib import *
      6 from pysam.cutils import *
      7 import pysam.cutils as cutils

ImportError: dynamic module does not define init function (initlibchtslib)

**Comment by bioinformed** [comment] 2016-10-27 00:35
Duplicate of #360.  Please try the fix in https://github.com/bioinformed/pysam

**Closed by bioinformed** 2016-10-27 00:35 UTC
