### ISSUE TITLE
Missing data when iterating through pileup

### ISSUE THREAD

**Issue by standage** [pysam-developers/pysam#1006] opened 2021-04-21 21:05 UTC
I occasionally observe missing data when using pysam to iterate through pileups. Today I was able to isolate an example with a single read. Consider the following: there is some soft clipping required at the ends, but otherwise there is a match/mismatch at every position of the read alignment: no gaps. Yet when iterating through the pileup, the C aligned to offset 52 of the reference is skipped.

----------

The sequences.

```
$ cat refr.fasta
>refr
CTCTCTGAGCGATCTAGGCCTTAGTGAAGGCTGCTGCTTGGGAGGCTTCCCCCCCCAACCGTACTCCATGAGCACCCCCA
ACAGCTGAACCCTGCAACAGTAGCTGAGGCTACCTGCCTGGGCAGTGTGGAGGCAGCCTTGCTGGAAACCTCACCCCTGC
CCCCAGGCCCTAGCTGAATGAGGAGTGAGGGAGAAAGAGGGGAAGGGAGAGAAGAGGATGCTTGAGAAGCTGATGTAGTT
CTTCACCTTGACCGAGTTCCCTC
$ cat testread.fastq 
@read
CTGTGGCTGTTCAGGTGTCCTCCTTTCTCTCTGAGCCATCTAGGCCTTAGTGAAGGCTGCTGCTTGGGAGGCTTCCCCCCCCAACCGTACTCCATCAGCACCCCCGACAGCTGAACCCTGCAACAGCAGCTGAGGCTACCTGCCTGGGCAGTGTGGAGGCAGCCTTGCTGGAAACCTCACCCCTGCCCACAGGCCCTAGCTGAATGAGGAGTGAGGGAGAAAGAGGGGAAGGGAGAGAAGAGGATGCTTGAGAAGCTGATGTAGTTCTTCACCTTGACCGAGTTCCCTCCCCACTTCAGACCTGT
+
>A1A11>11BBDGGCA1BBGFGGGGG1AAAFFG11B00111B1FFB1F11212DA1EFA/G1FE1B?/B//EE00?00-//>@E/?/E/EE/F1F/11B@GGC?EGGGG/<11@/@FEF00<GBHHGDFFGCG</FHG@FD<A.GF<G<0AGB0/C1?/0<//FF0C1GGDB000AEGGEE?GGF?01<>//>/0GFG1DHEEDGF1B11GG00B1FHFHFCEG0E>0100ED2HFGG11ECFDEEBFGBDG1HFDGFGF1GA00HGDFB11BGE0E0EGGFB00?AAA111EDDBFDC@?A>1A
```

Alignment.
```
$ bwa index refr.fasta 
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index refr.fasta
[main] Real time: 0.024 sec; CPU: 0.007 sec
$ bwa mem refr.fasta testread.fastq | samtools view -b | samtools sort -o testread.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 1 sequences (305 bp)...
[M::mem_process_seqs] Processed 1 reads in 0.000 CPU sec, 0.002 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem refr.fasta testread.fastq
[main] Real time: 0.004 sec; CPU: 0.005 sec
$ samtools index testread.bam 
```

And processing with pysam. Note that nothing is printed for offset 52.
```
$ python
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:16) 
[GCC Clang 11.0.1] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__version__
'0.16.0.1'
>>> bam = pysam.AlignmentFile("testread.bam", "rb")
>>> for column in bam.pileup("refr"):
...   for record in column.pileups:
...     print(column.pos, record.alignment.query_sequence[record.query_position])
... 
0 C
1 T
2 C
3 T
4 C
5 T
6 G
7 A
8 G
9 C
10 C
11 A
12 T
13 C
14 T
15 A
16 G
17 G
18 C
19 C
20 T
21 T
22 A
23 G
24 T
25 G
26 A
27 A
28 G
29 G
30 C
31 T
32 G
33 C
34 T
35 G
36 C
37 T
38 T
39 G
40 G
41 G
42 A
43 G
44 G
45 C
46 T
47 T
48 C
49 C
50 C
51 C
53 C
54 C
55 C
56 A
57 A
58 C
59 C
60 G
61 T
62 A
63 C
64 T
65 C
66 C
67 A
68 T
69 C
70 A
71 G
72 C
73 A
74 C
75 C
76 C
77 C
78 C
79 G
80 A
81 C
82 A
83 G
84 C
85 T
86 G
87 A
88 A
89 C
90 C
91 C
92 T
93 G
94 C
95 A
96 A
97 C
98 A
99 G
100 C
101 A
102 G
103 C
104 T
105 G
106 A
107 G
108 G
109 C
110 T
111 A
112 C
113 C
114 T
115 G
116 C
117 C
118 T
119 G
120 G
121 G
122 C
123 A
124 G
125 T
126 G
127 T
128 G
129 G
130 A
131 G
132 G
133 C
134 A
135 G
136 C
137 C
138 T
139 T
140 G
141 C
142 T
143 G
144 G
145 A
146 A
147 A
148 C
149 C
150 T
151 C
152 A
153 C
154 C
155 C
156 C
157 T
158 G
159 C
160 C
161 C
162 A
163 C
164 A
165 G
166 G
167 C
168 C
169 C
170 T
171 A
172 G
173 C
174 T
175 G
176 A
177 A
178 T
179 G
180 A
181 G
182 G
183 A
184 G
185 T
186 G
187 A
188 G
189 G
190 G
191 A
192 G
193 A
194 A
195 A
196 G
197 A
198 G
199 G
200 G
201 G
202 A
203 A
204 G
205 G
206 G
207 A
208 G
209 A
210 G
211 A
212 A
213 G
214 A
215 G
216 G
217 A
218 T
219 G
220 C
221 T
222 T
223 G
224 A
225 G
226 A
227 A
228 G
229 C
230 T
231 G
232 A
233 T
234 G
235 T
236 A
237 G
238 T
239 T
240 C
241 T
242 T
243 C
244 A
245 C
246 C
247 T
248 T
249 G
250 A
251 C
252 C
253 G
254 A
255 G
256 T
257 T
258 C
259 C
260 C
261 T
262 C
>>>
```

**Comment by jmarshall** [comment] 2021-04-21 22:36
This is the base (see `00-//` in the QUAL string) whose ASCII-encoded base quality is `-`, namely 12.

Similarly to `samtools mpileup`, the default minimum base quality threshold is 13. If you use `bam.pileup("refr", min_base_quality = 0)` this base will appear in the output.

Duplicate of #735 and #1002.

**Closed by jmarshall** 2021-04-21 22:36 UTC

**Comment by standage** [comment] 2021-04-22 01:38
Wonderful. Thanks for the prompt response!
