### ISSUE TITLE
number of mapped and unmapped reads when using cram file

### ISSUE THREAD

**Issue by wdecoster** [pysam-developers/pysam#556] opened 2017-10-25 21:04 UTC
Upon testing, if a script I wrote would also work using cram files, I stumbled upon a strange output. I haven't been using cram files that often - so my apologies if I missed something basic.

System:  
Ubuntu16.04  
Python 3.6.3 |Anaconda  
pysam 0.12.0.1  

I created a cram file:
```bash
minimap2 -a -t 4 genome.fa reads.fastq.gz | \
 samtools sort -O bam -l 0 - | \
 samtools view -T genome.fa -C -o alignment.cram -
```

I want to parse this file using pysam:
```python
>>> import pysam
>>> samfile = pysam.AlignmentFile("alignment.cram", "rc")
>>> samfile.mapped
0
>>> samfile.unmapped
139636578540408
>>> samfile.is_cram
True
>>> samfile.has_index()
True
>>> samfile.references
('1', '10', '11', '12',...)  # etc, output as expected
>>> for read in samfile.fetch():
...   print(read.query_length)
... 
Container header CRC32 failure
Container header CRC32 failure
Container header CRC32 failure
...  # more of the same message
```

While samtools flagstat produces this output: (just a small dataset I have for testing)
```
1328 + 0 in total (QC-passed reads + QC-failed reads)
183 + 0 secondary
145 + 0 supplementary
0 + 0 duplicates
1187 + 0 mapped (89.38% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

Do you have any pointers about what's going wrong? 

Cheers,
Wouter

**Comment by AndreasHeger** [comment] 2017-10-27 08:20
Thanks, not sure what could be the problem. Could you share the CRAM file that causes the issue? Otherwise, the next thing I would try is to see if the same issue occurs if the output is BAM, i.e. exact same commands, but -B instead of -C.

Also, I wonder if you could post the full command history? There are several CRAM files in play (alignment.cram, part2.cram)

**Comment by wdecoster** [comment] 2017-10-27 08:37
I can't share this particular cram file, but I will try to replicate with another I can share.

part2.cram is actually the same as alignment.cram - I forgot to change the name and I have edited my post now to clarify.

**Comment by AndreasHeger** [comment] 2017-10-27 08:42
Thanks. Happy to help sort this out.

**Comment by wdecoster** [comment] 2017-10-27 09:11
You can find another cram file here: https://www.dropbox.com/s/bli4hjsfurh6u8s/alignment.cram?dl=0
It's again a set of 1000 oxford nanopore reads. The alignment.fa is here: 
https://www.dropbox.com/s/8k6dpkjw0a5tiaa/GCF_000240185.1_ASM24018v2_genomic.fna?dl=0
If you want you can find the reads here: https://www.dropbox.com/s/uvie5q20awh9gwx/reads.fastq.gz?dl=0


I'm now working on a different machine (CentOS6) but the python and pysam version are the same.

Strangely enough, now the fetch does work. I'm not sure what's different. I'll have to test this again at home.


```python
>>> for read in samfile.fetch():
...   print(read.query_length)
```
The mapped/unmapped still show the same behaviour

```python
>>> samfile.mapped
0
>>> samfile.unmapped
4994590205196321612
```

As you suggested I also tried in bam format:
```bash
minimap2 -a -t 4 genome.fa reads.fastq.gz | \
 samtools sort -O bam -l 0 - | \
 samtools view -T genome.fa -B -o alignment.bam -
```

Here the behaviour looks sane:
```python
>>> import pysam
>>> samfile = pysam.AlignmentFile("alignment.bam", "rb")
>>> samfile.mapped
1197
>>> samfile.unmapped
40
```

Which corresponds to samtools flagstat on that bam and cram (output is identical):
```
1237 + 0 in total (QC-passed reads + QC-failed reads)
82 + 0 secondary
155 + 0 supplementary
0 + 0 duplicates
1197 + 0 mapped (96.77% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by dpryan79** [comment] 2017-11-05 23:07
For what it's worth, all CRAM files will show 0 mapped reads and some large number of unmapped reads. The cause for this is that alignment statistics aren't present in the index. I also happened to have just stumbled across this issue when testing some stuff with CRAM :(

XRef: https://github.com/samtools/samtools/issues/727

**Comment by dpryan79** [comment] 2017-11-06 14:37
@AndreasHeger: What do you think about making `bam.mapped` and `bam.unmapped` writable in the case of a CRAM file? At least in deepTools we have the problem that we pass file handles around between functions and being able to set these to appropriate values right away would be convenient.

**Comment by AndreasHeger** [comment] 2017-11-10 12:42
Thanks. My gut feeling is that making bam.mapped and bam.unmapped writeable would be confusing. I think the expectation would then be that this information would somehow be made persistent, which is not possible.

**Comment by dpryan79** [comment] 2017-11-10 12:48
Fair enough, I'll reimplement things in deepTools to store this as a separate variable that gets passed around as needed. BTW, this issue can probably get closed, since it's a cram limitation.

**Comment by AndreasHeger** [comment] 2017-11-10 13:10
Thanks, closing!

**Closed by AndreasHeger** 2017-11-10 13:10 UTC
