### ISSUE TITLE
problem with libchtslib

### ISSUE THREAD

**Issue by Niazevedo** [pysam-developers/pysam#421] opened 2017-03-21 21:46 UTC
Hi. I'm using a software that requires Pysam and this error is appearing. I downloaded Pysam with bioconda and it is already updated.

File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/init.py", line 5, in 
from pysam.libchtslib import *
ImportError: dlopen(/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libhts.1.dylib
Referenced from: /Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so
Reason: image not found

**Comment by kyleabeauchamp** [comment] 2017-03-21 21:59
Can you also open an issue on the bioconda tracker so those folks can see this?

**Comment by kyleabeauchamp** [comment] 2017-03-21 22:02
Can you also see which version of htslib you have installed via conda?  I'm wondering if this is due to having 1.4 HTSLib installed alongside 1.3-based pysam.

**Comment by kyleabeauchamp** [comment] 2017-03-21 22:02
Samtools too, get the version there.

**Comment by Niazevedo** [comment] 2017-03-21 22:08
pysam                     0.10.0                   py27_2    bioconda

htslib                    1.4                           0    bioconda

samtools                  1.4                           0    bioconda

**Comment by kyleabeauchamp** [comment] 2017-03-21 22:11
Thanks, I have confirmed that this is due to having HTSLib 1.4 installed. We need to fix HTSLib=1.3.1 in the pysam recipe.

**Comment by kyleabeauchamp** [comment] 2017-03-21 22:15
I think this PR should fix: https://github.com/bioconda/bioconda-recipes/pull/4233

**Comment by Niazevedo** [comment] 2017-03-21 23:21
I know have all three altered packages in the recipe to version 1.3.1 and the error still appears

**Comment by Niazevedo** [comment] 2017-03-22 10:37
I have upgraded to the new pysam version in the bioconda and samtools, htslib and bcftools has been downgraded but there is still the same error.

**Comment by kyleabeauchamp** [comment] 2017-03-22 16:25
I think the next step in debugging an issue like this is to see why the libraries can't load, you might try running otool -L on the various SO files in your pysam site-packages directory.

**Comment by Niazevedo** [comment] 2017-03-22 17:56
Danielas-Mac:pysam niazevedo$ for file in *.so
> do
> otool -L $file
> done
libcalignedsegment.so:
	@rpath/python2.7/site-packages/pysam/libcalignedsegment.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcalignmentfile.so:
	@rpath/python2.7/site-packages/pysam/libcalignmentfile.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcbcf.so:
	@rpath/python2.7/site-packages/pysam/libcbcf.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcbgzf.so:
	@rpath/python2.7/site-packages/pysam/libcbgzf.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcfaidx.so:
	@rpath/python2.7/site-packages/pysam/libcfaidx.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libchtslib.so:
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcsamfile.so:
	@rpath/python2.7/site-packages/pysam/libcsamfile.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libctabix.so:
	@rpath/python2.7/site-packages/pysam/libctabix.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libctabixproxies.so:
	@rpath/python2.7/site-packages/pysam/libctabixproxies.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcutils.so:
	@rpath/python2.7/site-packages/pysam/libcutils.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
libcvcf.so:
	@rpath/python2.7/site-packages/pysam/libcvcf.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libhts.1.dylib (compatibility version 1.0.0, current version 1.3.2)
	@rpath/python2.7/site-packages/pysam/libchtslib.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

**Comment by AndreasHeger** [comment] 2017-11-17 22:21
Closing this for now, please reopen if still an issue.

**Closed by AndreasHeger** 2017-11-17 22:22 UTC
