### ISSUE TITLE
count_coverage not count all reads

### ISSUE THREAD

**Issue by sravel** [pysam-developers/pysam#555] opened 2017-10-25 07:38 UTC
Hi, 

I want to use count and count_coverage function but I think there is a bug for count_coverage because when I do the sum of reads found with count_coverage, I don't have the same as found with count function.

```python
bamfile = pysam.AlignmentFile("GWT-5-AAA_BSV-OL_genbank_50pbajoutees.bam", "rb")
dicoRefSize = dict([ (dico["SN"], dico["LN"]) for dico in bamfile.header["SQ"] ])							# lit le header et retourne une liste des séquences avec leurs tailles
print(dicoRefSize)

for ref in bamfile.references: 							# parcours des séquences (chromosome, BAC, ...)
	refSize = dicoRefSize[ref]
	for pos in range(1,refSize):
		count = bamfile.count(ref,pos-1,pos, until_eof=True)
		count_coverage = dict([(letter,count[0]) for letter,count in zip(["A", "C", "G", "T"], bamfile.count_coverage(ref,pos-1,pos, read_callback='nofilter')) ])
		print("POS:{}\t\t{}\t\t{}\t{}".format(pos,count,count_coverage, sum(count_coverage.values())))
```
is print:
```bash
POS:1           93              {'C': 90, 'A': 0, 'G': 0, 'T': 0}       90
POS:2           177             {'C': 4, 'A': 0, 'G': 88, 'T': 83}      175
POS:3           203             {'C': 1, 'A': 5, 'G': 10, 'T': 186}     202
POS:4           323             {'A': 7, 'G': 8, 'T': 278, 'C': 20}     313
POS:5           427             {'A': 73, 'G': 338, 'T': 2, 'C': 3}     416

...
```
I see bam and I found for the first position one read with N.
but there is 2 C not count.
It's possible to add N count on count_coverage?

for position 2, one G not found
for position 3, one T not found
for position 4, one C and  8 T not found (one N found)
for position 5, 11 G not found
....

Thanks

RAVEL Sébastien

**Comment by lituan** [comment] 2017-11-01 02:40
by default, count_coverage will filter base with q quality-score less than 15, I think that's the cause.

count_coverage(self,reference=None,start=None,end=None,region=None,quality_threshold=15, read_callback=’all’)

**Comment by AndreasHeger** [comment] 2017-11-10 14:25
Thanks @lituan , closing this issue for now, please reopen if it is likely to be a bug.

**Closed by AndreasHeger** 2017-11-10 14:25 UTC
