### ISSUE TITLE
No version 0.16.0 wheels on pypi

### ISSUE THREAD

**Issue by cjw85** [pysam-developers/pysam#929] opened 2020-06-15 09:21 UTC
Its been a week or so since a source distribution for version 0.16.0 appeared on pypi, but there are no wheels available for this release.

**Comment by iosonofabio** [comment] 2020-06-16 07:00
Now there are wheels but AFAICT they are broken in terms of htslib dependency, e.g.: https://travis-ci.org/github/htseq/htseq/jobs/698814183 (see the end of the log).

Actually, every time pysam gets put onto pypi there is a transition period of a few days/weeks where the whole dependency chain breaks in the most curious ways. I'm sure it's hard to maintain and really appreciate the devs time and work, so I'm wondering how we could make that deployment a little more stable?

**Comment by AndreasHeger** [comment] 2020-06-16 21:00
Ah, sorry, about this. There is set up an automatic deployment of wheels in travis, but this failed. I build the wheels manually as before. The build worked without issue, but apparently something has changed. I will check. 

The problem is that I have very little time for pysam at the moment and am not doing much NGS analysis in my daily work.

**Comment by AndreasHeger** [comment] 2020-06-16 21:09
If you don't mind , I will close this issue and open a separate ticket about deployment.

**Comment by AndreasHeger** [comment] 2020-06-16 21:11
See #931 and #930

**Comment by cjw85** [comment] 2020-06-16 21:12
I guess there are now technically wheel on pypi ;)

**Closed** 2020-06-16 21:11 UTC
