### ISSUE TITLE
AlignmentFile.fetch(until_eof=True) locks up

### ISSUE THREAD

**Issue by innovate-invent** [pysam-developers/pysam#505] opened 2017-07-11 23:08 UTC
I have created a simplified test case for my issue.
fetch() seems to not pick up on the EOF if it is blocking before the EOF is transmitted.
This causes the program to lock up.
Python 3.5 pysam 11.2.1
```
import pysam, multiprocessing, sys

def p(pipeR):
    c = pysam.AlignmentFile(pipeR.fileno())
    d = pysam.AlignmentFile(sys.stdout, 'w', template=c)
    for r in c.fetch(until_eof=True): d.write(r)
    c.close()
    d.close()

a = pysam.AlignmentFile('singlePair250.bam')
pipeR, pipeW = multiprocessing.Pipe(False)
b = pysam.AlignmentFile(pipeW.fileno(), 'wbu', template=a)

proc = multiprocessing.Process(target=p, args=(pipeR,))
proc.start()

for r in a: b.write(r)
a.close()
b.close()
pipeW.close()

#proc = multiprocessing.Process(target=p, args=(pipeR,))
#proc.start()
proc.join()
```
Swapping the comments on proc allows the program to exit normally.

Here is my test data
```
@HD	VN:1.3	SO:coordinate
@SQ	SN:Test_Reference_250	LN:251
@PG	ID:bwa	PN:bwa	VN:0.7.13-r1126	CL:bwa sampe test_ref250.fa tmp1.sai tmp2.sai tmp1.fq tmp2.fq
Test_Reference_250_136_220_3:0:0_0:0:0_0	163	Test_Reference_250	136	60	70M	=	151	85	AAGGATTGTAGACAGGACATTAAATGACTTCTAGTCCCTAGAGTTCCCAATCACCTACCATCCCATCCTC	2222222222222222222222222222222222222222222222222222222222222222222222	XT:A:U	NM:i:3	SM:i:37	AM:i:37	X0:i:1	X1:i:0	XM:i:3	XO:i:0	XG:i:0	MD:Z:17A34T16A0
Test_Reference_250_136_220_3:0:0_0:0:0_0	83	Test_Reference_250	151	60	70M	=	136	-85	GAAATTAAATGACTTCTAGTCCCTAGAGTTCCCAATCTCCTACCATCCCATCCTAATATGACAGAAGTAA	2222222222222222222222222222222222222222222222222222222222222222222222	XT:A:U	NM:i:0	SM:i:37	AM:i:37	X0:i:1	X1:i:0	XM:i:0	XO:i:0	XG:i:0	MD:Z:70
```

**Comment by AndreasHeger** [comment] 2017-07-21 15:17
Thanks, I can reproduce this. 

Not 100% sure what exactly happens here. The issue is likely the behaviour of pysam when opening. If existing file objects or file handles are passed to AlignmentFile, the file descriptor will be duplicated using fdup. This is to prevent issues with a file object going out of scope unexpectedly. Basically, the following works:
```
with open("x.bam") in inf:
     pysam_file = AlignmentFile(inf.fileno())
pysam_file.fetch()
```
Without duplication, pysam_file.fetch() would fail. Also, you would get a double close when garbage collecting both the original file object and the derived AlignmentFile.

The option "duplicate_filehandle" to AlignmentFile controls this behaviour. The following works:
```
    c = pysam.AlignmentFile(pipeR.fileno(), duplicate_filehandle=False)
    pipeR.close()
    d = pysam.AlignmentFile(sys.stdout, 'w', template=c, duplicate_filehandle=False)
```
but produces ugly ignored exceptions about truncated files. 

Possibly related is what has been described here: https://stackoverflow.com/a/7942344 
```
What happens is that when two parallel child processes get started the second child inherits the pipes of the parent, so that when the parent calls self.parent_conn.close() the second child still has that pipe file descriptor open, so that the pipe file description doesn't get closed in the kernel (the reference count is more than 0), with the effect being that self.child_conn.recv_bytes() in the first parallel child process never read()s EOF and EOFError gets never thrown.
```

**Comment by AndreasHeger** [comment] 2017-07-21 15:39
The solution so far:

```
import pysam, multiprocessing, sys

def p(pipeR, pipeW):
    pipeW.close()
    c = pysam.AlignmentFile(pipeR.fileno(),
                            duplicate_filehandle=False)
    for r in c.fetch(until_eof=True):
        print(str(r))
    c.close()

pipeR, pipeW = multiprocessing.Pipe(False)
a = pysam.AlignmentFile('ex3.bam')
b = pysam.AlignmentFile(pipeW.fileno(), 'wbu', template=a, duplicate_filehandle=False)

proc = multiprocessing.Process(target=p, args=(pipeR, pipeW))
proc.start()
for r in a:
    b.write(r)

a.close()
b.close()
proc.join()
```
with output:
```
read_28833_29006_6945   99      0       32      20      10M1D25M        0       199     35      AGCTTAGCTAGCTACCTATATCTTGGTCTTGGCCG     array('B', [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 25, 27, 24, 14, 11, 5, 11, 17, 17, 26, 26, 27, 27, 27])      [('NM', 1), ('RG', 'L1'), ('PG', 'P1'), ('XT', 'U')]
read_28701_28881_323b   147     1       87      30      35M     1       499     35      ACCTATATCTTGGCCTTGGCCGATGCGGCCTTGCA     array('B', [27, 27, 27, 27, 27, 26, 27, 27, 27, 27, 22, 26, 25, 27, 27, 27, 21, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 22, 27, 27, 27, 27])     [('MF', 18), ('RG', 'L2'), ('PG', 'P2'), ('XT', 'R')]
read_28701_28881_323c   147     1       87      30      35M     1       499     35      ACCTATATCTTGGCCTTGGCCGATGCGGCCTTGCA     array('B', [27, 27, 27, 27, 27, 26, 27, 27, 27, 27, 22, 26, 25, 27, 27, 27, 21, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 22, 27, 27, 27, 27])     []
test_clipped1   99      1       996     20      4S6M1D20M5S     1       199     26      AGCTTAGCTAGCTACCTATATCTTGGTCTTGGCCG     array('B', [27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 25, 27, 24, 14, 11, 5, 11, 17, 17, 26, 26, 27, 27, 27])      [('NM', 1), ('RG', 'L1'), ('PG', 'P1'), ('XT', 'U')]
bgzf_close called
Exception ignored in: <bound method _ConnectionBase.__del__ of <multiprocessing.connection.Connection object at 0x2b463b783c88>>
Traceback (most recent call last):
  File "/ifs/home/andreas/miniconda3/envs/pysam-devel/lib/python3.6/multiprocessing/connection.py", line 132, in __del__
  File "/ifs/home/andreas/miniconda3/envs/pysam-devel/lib/python3.6/multiprocessing/connection.py", line 361, in _close
OSError: [Errno 9] Bad file descriptor
```
The issue is, that as various AlignmentFiles go out of scope, htslib closes the file handle, which causes the multiprocessing connections to fail once they go out of scope.

**Comment by AndreasHeger** [comment] 2017-07-21 15:42
There is probably a solution managing the various file descriptors (closing, duplicating) that would fully work, but my knowledge of multiprocessing is not deep enough.

**Comment by AndreasHeger** [comment] 2017-12-08 11:25
Closing this issue for now.

**Closed by AndreasHeger** 2017-12-08 11:25 UTC
