### ISSUE TITLE
Weird behavior from pysam.bcftools.mpileup with "Segmentation fault"

### ISSUE THREAD

**Issue by sbslee** [pysam-developers/pysam#944] opened 2020-07-23 08:59 UTC
Hi,

This is related to my previous issue (#928). I have been trying to resolve it without any success. However, I did see some interesting behavior. Basically, I found that if I run pysam.bcftools.mpileup with my MacBook Pro, it suddenly runs just fine:

SEUNGs-MacBook-Pro-2:Desktop seungbeenlee$ cat local.py
from pysam import bcftools
bcftools.mpileup()

SEUNGs-MacBook-Pro-2:Desktop seungbeenlee$ python3 local.py
Traceback (most recent call last):
  File "local.py", line 2, in <module>
    bcftools.mpileup()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'bcftools returned with error 1: stdout=, stderr=Error: mpileup requires the --fasta-ref option by default; use --no-reference to run without a fasta reference\n'

(Don’t worry about the error above. I didn’t provide any arguments to the command, so it makes sense I get this error.)

Now, when I do the same thing on a server, pysam gives a totally different kind of error:

(base) [sbslee@cm401 ~]$ cat server1.py 
from pysam import bcftools
bcftools.mpileup()

(base) [sbslee@cm401 ~]$ python3 server1.py 
Segmentation fault

This time, instead of getting an informative error, I get this “Segmentation fault”. Here, I’m using Anaconda and I tried this in a new, clean environment too.

This happens again in a completely different server:

[sbslee@grchead ~]$ cat server2.py 
from pysam import bcftools
bcftools.mpileup()

[sbslee@grchead ~]$ python3 server2.py 
Segmentation fault (core dumped)

Can someone please tell me why this is happening? The mere fact that it runs fine in my MacBook Pro gives me a hope that I can use bcftools.mpileup but I think I am stuck now… I really want to be able to use bcftools.mpileup for SNP calling (note that I’m aware about samtools.mpileup but its functionality for SNP calling is depreciated and shouldn’t be used for that purpose according to the manual: http://www.htslib.org/doc/samtools-mpileup.html).

Any help would be greatly appreciated.

**Comment by jmarshall** [comment] 2020-07-23 13:02
Duplicate of #928

**Closed by jmarshall** 2020-07-23 13:02 UTC
