### ISSUE TITLE
INFO Field Parsing String -127

### ISSUE THREAD

**Issue by paudano** [pysam-developers/pysam#371] opened 2016-11-04 20:31 UTC
When parsing INFO, a field with -127 becomes an empty tuple in `pysam.cbcf.VariantRecord.info`

Python: 3.5.2
Pysam: 0.9.1.4
* Also replicated in Pysam 0.8.4 on Python 2.7.12

Code to replicate (see "short.vcf" below).

```$ python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import pysam
>>> 
>>> vcf = pysam.VariantFile('short.vcf')
>>> 
>>> record = next(vcf)
>>> record.info['SVLEN']
()
>>> 
>>> record = next(vcf)
>>> record.info['SVLEN']
-126
>>> 
>>> record = next(vcf)
>>> record.info['SVLEN']
-128
>>> 
>>> 
>>> sys.version_info
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
>>> 
>>> pysam.__version__
'0.9.1.4'
>>>
```

short.vcf
```
##fileformat=VCFv4.2
##contig=<ID=chr1,length=248956422>
##INFO=<ID=END,Number=1,Type=Integer,Description="Reference end position of the variant">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between the REF and ALT alleles">
##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE
chr1	100000	TEST-127	C	<DEL>	100	PASS	END=100126;SVTYPE=DEL;SVLEN=-127	GT:CS:CD	1/1
chr1	200000	TEST-126	C	<DEL>	100	PASS	END=200125;SVTYPE=DEL;SVLEN=-126	GT:CS:CD	1/1
chr1	300000	TEST-128	C	<DEL>	100	PASS	END=300127;SVTYPE=DEL;SVLEN=-128	GT:CS:CD	1/1
```

**Comment by bioinformed** [comment] 2016-11-04 21:53
Thanks for the issue report!  The problem is clear and I'll hopefully have it triaged and solved quickly.

**Comment by bioinformed** [comment] 2016-11-18 16:31
Thanks again for the bug report.  Can you please try this fixed version in [my pysam repo](https://github.com/bioinformed/pysam)?

**Comment by paudano** [comment] 2016-11-18 17:12
Yes, it now works. I get -127 instead of ().


Python 3.5.2 (default, Nov  7 2016, 11:31:36)
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pysam
 >>> vcf = pysam.VariantFile('short.vcf')
 >>> record = next(vcf)
 >>> record.info['SVLEN']
-127
 >>> record = next(vcf)
 >>> record.info['SVLEN']
-126
 >>> record = next(vcf)
 >>> record.info['SVLEN']
-128
 >>>


Thank you!

**Comment by bioinformed** [comment] 2016-12-12 18:51
Fix will be merged shortly.

**Closed by bioinformed** 2016-12-12 18:51 UTC
